version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "monthly"
  - package-ecosystem: "swift"
    directory: "/darwin"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/windows"
    schedule:
      interval: "monthly"
