name: Feature requests
description: Suggest a new idea for gal.
labels: "✨ feature, \U0001F4A1 idia, \U0001F440 in triage"
assignees: natsuk4ze
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using gal!
        If you are looking for support, please check out our documentation.

          - https://github.com/natsuk4ze/gal/wiki
          - https://github.com/natsuk4ze/gal/discussions
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what you would like gal to be able to do.

        Consider attaching something showing what you are imagining:
         * images
         * videos
         * code samples
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.

        Describe the alternative solutions you've considered. Is there a package
        on pub.dev that already solves this?
    validations:
      required: true